mnist:
  output_dir: data/mnist
  spark_partitions: 8
  spark_driver_memory: 8g
  chunk_size: 2048
  normalize_mean: 0.1307
  normalize_std: 0.3081
  batch_size: 64
  epochs: 3
  seed: 42
train:
  lr: 0.001
  optimizer: adam
  momentum: 0.9
  weight_decay: 0.0
  scheduler: none
  step_size: 10
  gamma: 0.1
mlflow:
  run_description: "MNIST LeNet with Orca"
  experiment_name: mnist-orca
  tracking_uri: file:./mlruns
  registered_model_name: mnist-classifier
  register_stage: Staging
  promote_to_production: true
api:
  host: 0.0.0.0
  port: 8000
  stage_to_load: Production
  request_example_path: examples/sample_request.json
  timeout_seconds: 30
retrain:
  drift_threshold_psi: 0.2
  enable_auto_retrain: false
